-- CREAR LA BASE DE DATOS
CREATE DATABASE CAPAS_PRACTICA1;
GO

USE CAPAS_PRACTICA1;
GO

CREATE TABLE CLIENTES (
    ID_CLIENTES INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(50),
    DIRECCION VARCHAR(250)
);
GO

CREATE TABLE ENCABEZADO_FACTURA (
    ID_ENCABEZADO_FACTURA INT PRIMARY KEY,
    FECHA DATETIME,
    ID_CLIENTE INT,
    SUBTOTAL DECIMAL(5, 2),
    IMPUESTO DECIMAL(5, 2),
    MONTO_DESCUENTO DECIMAL(5, 2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);
GO

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(250),
    PRECIO_COMPRA DECIMAL(5, 2),
    PRECIO_VENTA DECIMAL(5, 2),
    GRABADO BIT
);
GO

CREATE TABLE DETALLE_FACTURA (
    ID_FACTURA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRIMARY KEY (ID_FACTURA, ID_PRODUCTO),
    FOREIGN KEY (ID_FACTURA) REFERENCES ENCABEZADO_FACTURA(ID_FACTURA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);
GO