--Proyecto Fase II
--Estudiante: Gabriela Gutiérrez Hernández
--Base de datos para la Clínica El Buen Vivir

--Creación de la base de datos

CREATE DATABASE BD_CLINICA
GO

USE BD_CLINICA
GO

--=====================================
--CREACIÓN DE TABLAS
--=====================================
CREATE TABLE PUESTO_TRABAJO (
	ID_PUESTO_TRABAJO INT IDENTITY(1,1) CONSTRAINT PK_ID_PUESTO_TRABAJO PRIMARY KEY,
	NOMBRE  VARCHAR(50) NOT NULL
);

CREATE TABLE FUNCIONARIOS (
	ID_FUNCIONARIO INT IDENTITY(1,1) CONSTRAINT PK_ID_FUNCIONARIO PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	P_APELLIDO	VARCHAR(15)	NOT NULL,
	S_APELLIDO	VARCHAR(15)	NOT NULL,
	FECHA_NACIMIENTO  DATETIME NOT NULL,
	GENERO CHAR(1),
	TELEFONO VARCHAR(20) NOT NULL,
	CORREO	VARCHAR(50)	NOT NULL UNIQUE,
	ID_PUESTO_TRABAJO INT NOT NULL CONSTRAINT FK_ID_PUESTO_TRABAJO FOREIGN KEY (ID_PUESTO_TRABAJO) REFERENCES PUESTO_TRABAJO(ID_PUESTO_TRABAJO),

)

CREATE TABLE ACCESO_SISTEMA (
	ID_ACCESO_SISTEMA INT IDENTITY(1,1) CONSTRAINT PK_ID_ACCESO_SISTEMA PRIMARY KEY,
	ID_FUNCIONARIO INT NOT NULL CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
	CLAVE VARCHAR(MAX) NOT NULL,
	NIVEL_ACCESO INT
)

CREATE TABLE BITACORA(
	ID_BITACORA INT IDENTITY(1,1) CONSTRAINT PK_ID_BITACORA PRIMARY KEY,
	ID_ACCESO_SISTEMA INT NOT NULL CONSTRAINT FK_ID_ACCESO_SISTEMA FOREIGN KEY(ID_ACCESO_SISTEMA) REFERENCES ACCESO_SISTEMA(ID_ACCESO_SISTEMA),
	FECHA_CITA  DATETIME NOT NULL,
	DESCRIPCION VARCHAR(500)
)

CREATE TABLE ESPECIALIDADES (
	ID_ESPECIALIDAD INT IDENTITY(1,1) CONSTRAINT PK_ID_ESPECIALIDAD PRIMARY KEY,
	NOMBRE_ESP VARCHAR(50)
)

CREATE TABLE FUNCIONARIOS_ESPECIALIDADES (
	ID_FUNCIONARIO_ESPECIALIDAD INT IDENTITY(1,1) CONSTRAINT PK_ID_FUNCIONARIO_ESPECIALIDAD PRIMARY KEY,
	ID_FUNCIONARIO INT NOT NULL CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
	ID_ESPECIALIDAD INT NOT NULL CONSTRAINT KF_ID_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD)
)


CREATE TABLE PACIENTES (
	ID_PACIENTE INT IDENTITY(1,1) CONSTRAINT PK_ID_PACIENTE PRIMARY KEY,
	NOMBRE  VARCHAR(50), 
	P_APELLIDO	VARCHAR(15)	NOT NULL,
	S_APELLIDO	VARCHAR(15)	NOT NULL,
	FECHA_NACIMIENTO  DATETIME NOT NULL,
	GENERO CHAR(1),
	TELEFONO VARCHAR(20) NOT NULL,
	CORREO	VARCHAR(50)	NOT NULL UNIQUE
)

CREATE TABLE ESPECIALISTAS (
	ID_ESPECIALISTA INT IDENTITY(1,1) CONSTRAINT PK_ID_ESPECIALISTA PRIMARY KEY,
	ID_ESPECIALIDAD INT NOT NULL CONSTRAINT FK_ID_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD),
	ID_FUNCIONARIO INT NOT NULL CONSTRAINT FK2_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
	ID_PUESTO_TRABAJO INT NOT NULL CONSTRAINT FK2_ID_PUESTO_TRABAJO FOREIGN KEY (ID_PUESTO_TRABAJO) REFERENCES PUESTO_TRABAJO(ID_PUESTO_TRABAJO),
	HORARIO_DISPONIBLE DATETIME
)

CREATE TABLE CITAS (
	ID_CITAS INT IDENTITY(1,1) CONSTRAINT PK_ID_CITAS PRIMARY KEY,
	ID_PACIENTE INT NOT NULL CONSTRAINT FK_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
	ID_ESPECIALISTA INT NOT NULL CONSTRAINT FK_ID_ESPECIALISTA FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA),
	FECHA_CITA  DATETIME 
)

CREATE TABLE PAGOS (
	ID_PAGOS INT IDENTITY(1,1) CONSTRAINT PK_ID_PAGOS PRIMARY KEY,
	ID_CITAS INT NOT NULL CONSTRAINT FK_ID_CITAS FOREIGN KEY (ID_CITAS) REFERENCES CITAS(ID_CITAS),
	ID_PACIENTE INT NOT NULL CONSTRAINT FK2_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
	MONTO DECIMAL(5,2) NOT NULL,
	FECHA_PAGO DATETIME NOT NULL,
	FORMA_PAGO VARCHAR(35) NOT NULL,
	DESCUENTO DECIMAL(5,2) NOT NULL,
	MONTO_FINAL DECIMAL(5,2)
)


CREATE TABLE HORARIOS_ESPECIALISTAS (
	ID_HORARIO_ESPECIALISTA INT IDENTITY(1,1) CONSTRAINT PK_ID_HORARIO_ESPECIALISTA PRIMARY KEY,
	ID_ESPECIALISTA INT NOT NULL CONSTRAINT FK_ID_ESPECIALISTA FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA),
	ID_FUNCIONARIO INT NOT NULL CONSTRAINT FK3_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
	DIA DATETIME,
	HORA_INICIO TIME,
	HORA_FIN  TIME
)

CREATE TABLE DIAGNOSTICOS (
	ID_DIAGNOSTICO INT IDENTITY(1,1) CONSTRAINT PK_ID_DIAGNOSTICO PRIMARY KEY,
	DESCRIPCION VARCHAR(50),
)

CREATE TABLE SIGNOS_VITALES (
	ID_SIGNOS_VITALES INT IDENTITY(1,1) CONSTRAINT PK_ID_SIGNOS_VITALES PRIMARY KEY,
	DESCRIPCION VARCHAR(50),
	PRESION DECIMAL(5,2),
	TEMPERATURA DECIMAL(5,2),
	ESTATURA DECIMAL(5,2),
	PESO DECIMAL (5,2)
)

CREATE TABLE MEDICAMENTOS (
	ID_MEDICAMENTOS INT IDENTITY(1,1) CONSTRAINT PK_ID_MEDICAMENTOS PRIMARY KEY,
	DESCRIPCION VARCHAR(50)
)

CREATE TABLE LABORATORIOS (
	ID_LABORATORIO INT IDENTITY(1,1) CONSTRAINT PK_ID_LABORATORIO PRIMARY KEY,
	DESCRIPCION VARCHAR(50)
)

CREATE TABLE HISTORIAL_CLINICO (
	ID_HISTORIAL_CLINICO INT IDENTITY(1,1) CONSTRAINT PK_ID_HISTORIAL_CLINICO  PRIMARY KEY,
	ID_PACIENTE INT NOT NULL CONSTRAINT FK3_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
	ID_ESPECIALISTA INT NOT NULL CONSTRAINT FK2_ID_ESPECIALISTA FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA),
	ID_DIAGNOSTICO INT NOT NULL CONSTRAINT FK_ID_DIAGNOSTICO FOREIGN KEY (ID_DIAGNOSTICO) REFERENCES DIAGNOSTICOS(ID_DIAGNOSTICO),
	ID_MEDICAMENTOS INT NOT NULL CONSTRAINT FK_ID_MEDICAMENTOS FOREIGN KEY (ID_MEDICAMENTOS) REFERENCES MEDICAMENTOS(ID_MEDICAMENTOS),
	FECHA_CONSULTA DATETIME,
	ID_SIGNOS_VITALES INT NOT NULL CONSTRAINT FK_ID_SIGNOS_VITALES FOREIGN KEY (ID_SIGNOS_VITALES) REFERENCES SIGNOS_VITALES(ID_SIGNOS_VITALES),
	ID_LABORATORIO INT NOT NULL CONSTRAINT FK_ID_LABORATORIO FOREIGN KEY (ID_LABORATORIO) REFERENCES LABORATORIOS(ID_LABORATORIO)
)